/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jcafe_noregistration;

/**
 *
 * @author My PC
 */
public class CoffeePanel extends javax.swing.JFrame {
    private MainMenuPanel mainMenuPanel;

    /**
     * Creates new form CoffeePanel
     */
    public CoffeePanel(MainMenuPanel mainMenuPanel) {
        initComponents();
        this.mainMenuPanel = mainMenuPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cappucinoBtn = new javax.swing.JButton();
        americanoBtn1 = new javax.swing.JButton();
        mochaBtn = new javax.swing.JButton();
        latteBtn = new javax.swing.JButton();
        spanishBtn = new javax.swing.JButton();
        flatwhiteBtn = new javax.swing.JButton();
        macchiatobtn = new javax.swing.JButton();
        espressoBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cappucinoBtn.setBackground(new java.awt.Color(249, 246, 238));
        cappucinoBtn.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        cappucinoBtn.setForeground(new java.awt.Color(169, 120, 83));
        cappucinoBtn.setText("Cappucino");
        cappucinoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cappucinoBtnActionPerformed(evt);
            }
        });

        americanoBtn1.setBackground(new java.awt.Color(249, 246, 238));
        americanoBtn1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        americanoBtn1.setForeground(new java.awt.Color(169, 120, 83));
        americanoBtn1.setText("Americano");
        americanoBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                americanoBtn1ActionPerformed(evt);
            }
        });

        mochaBtn.setBackground(new java.awt.Color(249, 246, 238));
        mochaBtn.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        mochaBtn.setForeground(new java.awt.Color(169, 120, 83));
        mochaBtn.setText("Mocha");
        mochaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mochaBtnActionPerformed(evt);
            }
        });

        latteBtn.setBackground(new java.awt.Color(249, 246, 238));
        latteBtn.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        latteBtn.setForeground(new java.awt.Color(169, 120, 83));
        latteBtn.setText("Latte");
        latteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                latteBtnActionPerformed(evt);
            }
        });

        spanishBtn.setBackground(new java.awt.Color(249, 246, 238));
        spanishBtn.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        spanishBtn.setForeground(new java.awt.Color(169, 120, 83));
        spanishBtn.setText("Spanish");
        spanishBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spanishBtnActionPerformed(evt);
            }
        });

        flatwhiteBtn.setBackground(new java.awt.Color(249, 246, 238));
        flatwhiteBtn.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        flatwhiteBtn.setForeground(new java.awt.Color(169, 120, 83));
        flatwhiteBtn.setText("Flat White");
        flatwhiteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flatwhiteBtnActionPerformed(evt);
            }
        });

        macchiatobtn.setBackground(new java.awt.Color(249, 246, 238));
        macchiatobtn.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        macchiatobtn.setForeground(new java.awt.Color(169, 120, 83));
        macchiatobtn.setText("Macchiato");
        macchiatobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                macchiatobtnActionPerformed(evt);
            }
        });

        espressoBtn.setBackground(new java.awt.Color(249, 246, 238));
        espressoBtn.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        espressoBtn.setForeground(new java.awt.Color(169, 120, 83));
        espressoBtn.setText("Espresso");
        espressoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espressoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(flatwhiteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(espressoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(latteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(americanoBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(spanishBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(macchiatobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mochaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cappucinoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(284, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cappucinoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(americanoBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mochaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(latteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(macchiatobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(espressoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spanishBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flatwhiteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cappucinoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cappucinoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cappucinoBtnActionPerformed

    private void americanoBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_americanoBtn1ActionPerformed
        // TODO add your handling code here:
        
        CoffeOptions options = new CoffeOptions(this.mainMenuPanel, "Americano");
        options.setVisible(true);
        this.dispose();
       
    }//GEN-LAST:event_americanoBtn1ActionPerformed

    private void mochaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mochaBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mochaBtnActionPerformed

    private void latteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_latteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_latteBtnActionPerformed

    private void spanishBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spanishBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spanishBtnActionPerformed

    private void flatwhiteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flatwhiteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flatwhiteBtnActionPerformed

    private void macchiatobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_macchiatobtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_macchiatobtnActionPerformed

    private void espressoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espressoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_espressoBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoffeePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoffeePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoffeePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoffeePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainMenuPanel mainMenu = new MainMenuPanel();
                new CoffeePanel(mainMenu).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton americanoBtn1;
    private javax.swing.JButton cappucinoBtn;
    private javax.swing.JButton espressoBtn;
    private javax.swing.JButton flatwhiteBtn;
    private javax.swing.JButton latteBtn;
    private javax.swing.JButton macchiatobtn;
    private javax.swing.JButton mochaBtn;
    private javax.swing.JButton spanishBtn;
    // End of variables declaration//GEN-END:variables
}
