/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jcafe_noregistration;

/**
 *
 * @author My PC
 */
public class JuicesPanel extends javax.swing.JFrame {

    /**
     * Creates new form JuicesPanel
     */
    public JuicesPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grapeBtn = new javax.swing.JButton();
        appleBtn = new javax.swing.JButton();
        pineappleBtn = new javax.swing.JButton();
        orangeBtn = new javax.swing.JButton();
        mangoBtn = new javax.swing.JButton();
        strawberryBtn = new javax.swing.JButton();
        lemonadeBtn = new javax.swing.JButton();
        watermelonBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        grapeBtn.setBackground(new java.awt.Color(249, 246, 238));
        grapeBtn.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        grapeBtn.setForeground(new java.awt.Color(169, 120, 83));
        grapeBtn.setText("GRAPE");
        grapeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grapeBtnActionPerformed(evt);
            }
        });

        appleBtn.setBackground(new java.awt.Color(249, 246, 238));
        appleBtn.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        appleBtn.setForeground(new java.awt.Color(169, 120, 83));
        appleBtn.setText("Apple");
        appleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appleBtnActionPerformed(evt);
            }
        });

        pineappleBtn.setBackground(new java.awt.Color(249, 246, 238));
        pineappleBtn.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        pineappleBtn.setForeground(new java.awt.Color(169, 120, 83));
        pineappleBtn.setText("Pineapple ");
        pineappleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pineappleBtnActionPerformed(evt);
            }
        });

        orangeBtn.setBackground(new java.awt.Color(249, 246, 238));
        orangeBtn.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        orangeBtn.setForeground(new java.awt.Color(169, 120, 83));
        orangeBtn.setText("Orange Juice");
        orangeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orangeBtnActionPerformed(evt);
            }
        });

        mangoBtn.setBackground(new java.awt.Color(249, 246, 238));
        mangoBtn.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        mangoBtn.setForeground(new java.awt.Color(169, 120, 83));
        mangoBtn.setText("Mango Juice");
        mangoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mangoBtnActionPerformed(evt);
            }
        });

        strawberryBtn.setBackground(new java.awt.Color(249, 246, 238));
        strawberryBtn.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        strawberryBtn.setForeground(new java.awt.Color(169, 120, 83));
        strawberryBtn.setText("Strawberry");
        strawberryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strawberryBtnActionPerformed(evt);
            }
        });

        lemonadeBtn.setBackground(new java.awt.Color(249, 246, 238));
        lemonadeBtn.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lemonadeBtn.setForeground(new java.awt.Color(169, 120, 83));
        lemonadeBtn.setText("Lemonade");
        lemonadeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lemonadeBtnActionPerformed(evt);
            }
        });

        watermelonBtn.setBackground(new java.awt.Color(249, 246, 238));
        watermelonBtn.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        watermelonBtn.setForeground(new java.awt.Color(169, 120, 83));
        watermelonBtn.setText("Watermelon");
        watermelonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                watermelonBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lemonadeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(grapeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pineappleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mangoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(strawberryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(watermelonBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(appleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(orangeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(283, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orangeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mangoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pineappleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(watermelonBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grapeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(strawberryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lemonadeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void grapeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grapeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grapeBtnActionPerformed

    private void appleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appleBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_appleBtnActionPerformed

    private void pineappleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pineappleBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pineappleBtnActionPerformed

    private void orangeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orangeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orangeBtnActionPerformed

    private void mangoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mangoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mangoBtnActionPerformed

    private void strawberryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strawberryBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_strawberryBtnActionPerformed

    private void lemonadeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lemonadeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lemonadeBtnActionPerformed

    private void watermelonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_watermelonBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_watermelonBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JuicesPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JuicesPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JuicesPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuicesPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JuicesPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appleBtn;
    private javax.swing.JButton grapeBtn;
    private javax.swing.JButton lemonadeBtn;
    private javax.swing.JButton mangoBtn;
    private javax.swing.JButton orangeBtn;
    private javax.swing.JButton pineappleBtn;
    private javax.swing.JButton strawberryBtn;
    private javax.swing.JButton watermelonBtn;
    // End of variables declaration//GEN-END:variables
}
