/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jcafe_noregistration;

/**
 *
 * @author My PC
 */
public class PastryPanel extends javax.swing.JFrame {

    /**
     * Creates new form PastryPanel
     */
    public PastryPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        muffinBtn = new javax.swing.JButton();
        cinnamonBtn = new javax.swing.JButton();
        danishBtn = new javax.swing.JButton();
        croissantBtn = new javax.swing.JButton();
        eclairBtn = new javax.swing.JButton();
        cheesecakeBtn = new javax.swing.JButton();
        applepieBtn = new javax.swing.JButton();
        doughnutBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        muffinBtn.setBackground(new java.awt.Color(249, 246, 238));
        muffinBtn.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        muffinBtn.setForeground(new java.awt.Color(169, 120, 83));
        muffinBtn.setText("Muffin");
        muffinBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muffinBtnActionPerformed(evt);
            }
        });

        cinnamonBtn.setBackground(new java.awt.Color(249, 246, 238));
        cinnamonBtn.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        cinnamonBtn.setForeground(new java.awt.Color(169, 120, 83));
        cinnamonBtn.setText("Cinnamon Roll");
        cinnamonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinnamonBtnActionPerformed(evt);
            }
        });

        danishBtn.setBackground(new java.awt.Color(249, 246, 238));
        danishBtn.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        danishBtn.setForeground(new java.awt.Color(169, 120, 83));
        danishBtn.setText("Danish");
        danishBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                danishBtnActionPerformed(evt);
            }
        });

        croissantBtn.setBackground(new java.awt.Color(249, 246, 238));
        croissantBtn.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        croissantBtn.setForeground(new java.awt.Color(169, 120, 83));
        croissantBtn.setText("Croissant");
        croissantBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                croissantBtnActionPerformed(evt);
            }
        });

        eclairBtn.setBackground(new java.awt.Color(249, 246, 238));
        eclairBtn.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        eclairBtn.setForeground(new java.awt.Color(169, 120, 83));
        eclairBtn.setText("Eclair");
        eclairBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eclairBtnActionPerformed(evt);
            }
        });

        cheesecakeBtn.setBackground(new java.awt.Color(249, 246, 238));
        cheesecakeBtn.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        cheesecakeBtn.setForeground(new java.awt.Color(169, 120, 83));
        cheesecakeBtn.setText("Cheesecake ");
        cheesecakeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheesecakeBtnActionPerformed(evt);
            }
        });

        applepieBtn.setBackground(new java.awt.Color(249, 246, 238));
        applepieBtn.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        applepieBtn.setForeground(new java.awt.Color(169, 120, 83));
        applepieBtn.setText("Apple Pie");
        applepieBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applepieBtnActionPerformed(evt);
            }
        });

        doughnutBtn.setBackground(new java.awt.Color(249, 246, 238));
        doughnutBtn.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        doughnutBtn.setForeground(new java.awt.Color(169, 120, 83));
        doughnutBtn.setText("Doughnut");
        doughnutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doughnutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cheesecakeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(doughnutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cinnamonBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(croissantBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(eclairBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(applepieBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(muffinBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(danishBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(283, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(danishBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(croissantBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(muffinBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cinnamonBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(applepieBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doughnutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eclairBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cheesecakeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void muffinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muffinBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_muffinBtnActionPerformed

    private void cinnamonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinnamonBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cinnamonBtnActionPerformed

    private void danishBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_danishBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_danishBtnActionPerformed

    private void croissantBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_croissantBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_croissantBtnActionPerformed

    private void eclairBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eclairBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eclairBtnActionPerformed

    private void cheesecakeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheesecakeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cheesecakeBtnActionPerformed

    private void applepieBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applepieBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_applepieBtnActionPerformed

    private void doughnutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doughnutBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doughnutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PastryPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PastryPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PastryPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PastryPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PastryPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applepieBtn;
    private javax.swing.JButton cheesecakeBtn;
    private javax.swing.JButton cinnamonBtn;
    private javax.swing.JButton croissantBtn;
    private javax.swing.JButton danishBtn;
    private javax.swing.JButton doughnutBtn;
    private javax.swing.JButton eclairBtn;
    private javax.swing.JButton muffinBtn;
    // End of variables declaration//GEN-END:variables
}
