/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jcafe_noregistration;

/**
 *
 * @author My PC
 */
public class PastaPanel extends javax.swing.JFrame {

    /**
     * Creates new form PastaPanel
     */
    public PastaPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lasagnaBtn = new javax.swing.JButton();
        alfredoBtn = new javax.swing.JButton();
        carbonaraBtn = new javax.swing.JButton();
        spaghettiBtn = new javax.swing.JButton();
        chickenBtn = new javax.swing.JButton();
        seafoodpastaBtn = new javax.swing.JButton();
        pestoBtn = new javax.swing.JButton();
        macandcheeseBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lasagnaBtn.setBackground(new java.awt.Color(249, 246, 238));
        lasagnaBtn.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        lasagnaBtn.setForeground(new java.awt.Color(169, 120, 83));
        lasagnaBtn.setText("Lasagna");
        lasagnaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lasagnaBtnActionPerformed(evt);
            }
        });

        alfredoBtn.setBackground(new java.awt.Color(249, 246, 238));
        alfredoBtn.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        alfredoBtn.setForeground(new java.awt.Color(169, 120, 83));
        alfredoBtn.setText("Alfredo");
        alfredoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alfredoBtnActionPerformed(evt);
            }
        });

        carbonaraBtn.setBackground(new java.awt.Color(249, 246, 238));
        carbonaraBtn.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        carbonaraBtn.setForeground(new java.awt.Color(169, 120, 83));
        carbonaraBtn.setText("Carbonara");
        carbonaraBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carbonaraBtnActionPerformed(evt);
            }
        });

        spaghettiBtn.setBackground(new java.awt.Color(249, 246, 238));
        spaghettiBtn.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        spaghettiBtn.setForeground(new java.awt.Color(169, 120, 83));
        spaghettiBtn.setText("Spaghetti");
        spaghettiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spaghettiBtnActionPerformed(evt);
            }
        });

        chickenBtn.setBackground(new java.awt.Color(249, 246, 238));
        chickenBtn.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        chickenBtn.setForeground(new java.awt.Color(169, 120, 83));
        chickenBtn.setText("Chicken Penne");
        chickenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chickenBtnActionPerformed(evt);
            }
        });

        seafoodpastaBtn.setBackground(new java.awt.Color(249, 246, 238));
        seafoodpastaBtn.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        seafoodpastaBtn.setForeground(new java.awt.Color(169, 120, 83));
        seafoodpastaBtn.setText("Seafood Pasta");
        seafoodpastaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seafoodpastaBtnActionPerformed(evt);
            }
        });

        pestoBtn.setBackground(new java.awt.Color(249, 246, 238));
        pestoBtn.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        pestoBtn.setForeground(new java.awt.Color(169, 120, 83));
        pestoBtn.setText("Pesto");
        pestoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pestoBtnActionPerformed(evt);
            }
        });

        macandcheeseBtn.setBackground(new java.awt.Color(249, 246, 238));
        macandcheeseBtn.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        macandcheeseBtn.setForeground(new java.awt.Color(169, 120, 83));
        macandcheeseBtn.setText("Mac & Cheese");
        macandcheeseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                macandcheeseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(seafoodpastaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(macandcheeseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(alfredoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(spaghettiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chickenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pestoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lasagnaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(carbonaraBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(283, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carbonaraBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spaghettiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lasagnaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alfredoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pestoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(macandcheeseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chickenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seafoodpastaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lasagnaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lasagnaBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lasagnaBtnActionPerformed

    private void alfredoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alfredoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alfredoBtnActionPerformed

    private void carbonaraBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carbonaraBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carbonaraBtnActionPerformed

    private void spaghettiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spaghettiBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spaghettiBtnActionPerformed

    private void chickenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chickenBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chickenBtnActionPerformed

    private void seafoodpastaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seafoodpastaBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seafoodpastaBtnActionPerformed

    private void pestoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pestoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pestoBtnActionPerformed

    private void macandcheeseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_macandcheeseBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_macandcheeseBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PastaPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PastaPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PastaPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PastaPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PastaPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alfredoBtn;
    private javax.swing.JButton carbonaraBtn;
    private javax.swing.JButton chickenBtn;
    private javax.swing.JButton lasagnaBtn;
    private javax.swing.JButton macandcheeseBtn;
    private javax.swing.JButton pestoBtn;
    private javax.swing.JButton seafoodpastaBtn;
    private javax.swing.JButton spaghettiBtn;
    // End of variables declaration//GEN-END:variables
}
