/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package jcafeloginandsignup;

import javax.swing.JOptionPane;

/**
 *
 * @author My PC
 */
public class OrderSummary extends javax.swing.JPanel {

    /**
     * Creates new form OrderSummary
     */
    public OrderSummary() {
        initComponents();
        showCartItems();
    }
    
    private void showCartItems() {
    jTextArea1.setText(""); // clear previous text

    for (String item : CartSystem.getCartItems()) {
        jTextArea1.append(item + "\n");
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ordersummaryframe = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        cancelorderBtn = new javax.swing.JButton();
        checkoutBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        discountdropdown = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        ordersummaryframe.setVisible(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Order Summary");

        cancelorderBtn.setText("Cancel Order");
        cancelorderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelorderBtnActionPerformed(evt);
            }
        });

        checkoutBtn.setText("Checkout");
        checkoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutBtnActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        discountdropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" ,"PWD (20%)", "Student (10%)", "Senior (20%)" }));
        discountdropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountdropdownActionPerformed(evt);
            }
        });

        jLabel2.setText("Select Discount:");

        javax.swing.GroupLayout ordersummaryframeLayout = new javax.swing.GroupLayout(ordersummaryframe.getContentPane());
        ordersummaryframe.getContentPane().setLayout(ordersummaryframeLayout);
        ordersummaryframeLayout.setHorizontalGroup(
            ordersummaryframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ordersummaryframeLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ordersummaryframeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ordersummaryframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ordersummaryframeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(discountdropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelorderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        ordersummaryframeLayout.setVerticalGroup(
            ordersummaryframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ordersummaryframeLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ordersummaryframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelorderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discountdropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18))
        );

        add(ordersummaryframe, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelorderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelorderBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelorderBtnActionPerformed

    private void checkoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutBtnActionPerformed
        // TODO add your handling code here:
        
        int total = 0;
        
        for (String item : CartSystem.getCartItems()) {
            try {
                String[] parts = item.split("Php ");
                if (parts.length > 1) {
                    String amountStr = parts[parts.length -1].trim();
                    total += Integer.parseInt(amountStr);
                }
            }catch (Exception e) {
                System.out.println("Error parsing Item: " + item);
            }
            
            
            String selected = (String) discountdropdown.getSelectedItem();
            
            int discountAmount = 0;
            
         
            if ("Student (10%)".equals(selected)){
                discountAmount = (int)(total * 0.10);
            } else if ("PWD (20%)".equals(selected) || "Senior(20%)".equals(selected)){
                discountAmount = (int)  (total * 0.20);
            } else if ("None".equals(selected)) {
                discountAmount = 0;
            }
            
            int finalAmount = total - discountAmount;
            
            JOptionPane.showMessageDialog(this,
                    "Original Total: Php " + total +
                    "\nDiscount: Php " + discountAmount +
                    "\nTotal Amount: Php " + finalAmount);
            
            CartSystem.clearCart();
            showCartItems();
            
        }
            
    }//GEN-LAST:event_checkoutBtnActionPerformed

    private void discountdropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountdropdownActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_discountdropdownActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelorderBtn;
    private javax.swing.JButton checkoutBtn;
    private javax.swing.JComboBox<String> discountdropdown;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JInternalFrame ordersummaryframe;
    // End of variables declaration//GEN-END:variables
}
